
spring:
  thymeleaf:
    cache: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community
    username: root
    password: 88888888
  mail:
    host: smtp.qq.com
    port: 465
    username: 1143702459@qq.com
    password: qrhurthifwnuhfjf # QQ邮箱的授权码
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.nowcoder.community.entity

# logger
logging:
  level:
    com.nowcoder.community: warn

#community
community:
  path:
    domain: http://localhost:8080
server:
  servlet:
    context-path: /community
